
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_actor
      description: "Test not null actors"
      columns:
          - name: ACTOR_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null